### ISSUE TITLE
VMS Moria 5 source code location

### ISSUE THREAD

**Issue by dchmelik** [dungeons-of-moria/vms-moria#1]
I don't have VMS Moria 5, which is a version not listed that you have, but check [ftp.FUNet.fi](http://www.nic.funet.fi/pub/unix/games/moria/vms/)

**Comment by mrcook** [comment]
Hi David, my apologies for the delayed response, I did not see your message.

That `vms50.tar.z` is actually `Moria UB 5.0`, another variant (see the `install.doc` file), worked on by William Palter and Nick B Triantos from the State University of New York at Buffalo, sometime around 1987.
